stages:
  - test
  - deploy
  - publish

test:
  stage: test
  image: node:15.6.0-alpine
  script:
    - npm ci
    - npm run lint

deploy:
  stage: deploy
  image: ruby:2.5.5-alpine3.10
  before_script:
    - apk update
    - apk add ruby-dev git curl
    - gem install dpl
  script:
    - dpl --provider=heroku --app=statusops --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
    - master
  when: manual

publish_services:
  stage: publish
  image: node:15.6.0-alpine
  before_script:
    - apk add curl
  script:
    - npm ci
    - node generate-services-csv.js services.csv
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file services.csv "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/services/1.0-SNAPSHOT/services.csv"'
